export type NutritionMealType = "desayuno" | "comida" | "cena" | "snack";
export type NutritionRisk = "lactosa" | "fructosa" | "sorbitol";

export type NutritionFood = {
  id: string;
  name: string;
  category: "proteina" | "carbohidrato" | "grasa" | "verdura" | "fruta" | "lacteo";
  kcal: number;
  protein: number;
  carbs: number;
  fats: number;
  defaultGrams: number;
  visualPortion: string;
  mealTypes: NutritionMealType[];
  risks: NutritionRisk[];
  notes?: string;
};

export type CalculatedIngredient = {
  food_id: string;
  name: string;
  grams: number;
  visual_portion: string;
  calories: number;
  protein: number;
  carbs: number;
  fats: number;
};

export const nutritionFoods: NutritionFood[] = [
  {
    id: "huevo_entero",
    name: "Huevo entero",
    category: "proteina",
    kcal: 143,
    protein: 12.6,
    carbs: 0.7,
    fats: 9.5,
    defaultGrams: 120,
    visualPortion: "2 huevos medianos",
    mealTypes: ["desayuno", "comida", "cena"],
    risks: [],
  },
  {
    id: "claras_huevo",
    name: "Claras de huevo",
    category: "proteina",
    kcal: 52,
    protein: 10.9,
    carbs: 0.7,
    fats: 0.2,
    defaultGrams: 180,
    visualPortion: "un vaso pequeño",
    mealTypes: ["desayuno", "comida", "cena"],
    risks: [],
  },
  {
    id: "pechuga_pollo",
    name: "Pechuga de pollo cocinada",
    category: "proteina",
    kcal: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    defaultGrams: 160,
    visualPortion: "una palma y media",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "pavo_filete",
    name: "Filete de pavo cocinado",
    category: "proteina",
    kcal: 150,
    protein: 29,
    carbs: 0,
    fats: 3.2,
    defaultGrams: 160,
    visualPortion: "una palma y media",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "ternera_magra",
    name: "Ternera magra cocinada",
    category: "proteina",
    kcal: 190,
    protein: 29,
    carbs: 0,
    fats: 8,
    defaultGrams: 150,
    visualPortion: "una palma grande",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "atun_natural",
    name: "Atún al natural escurrido",
    category: "proteina",
    kcal: 116,
    protein: 25.5,
    carbs: 0,
    fats: 0.8,
    defaultGrams: 120,
    visualPortion: "una lata grande escurrida",
    mealTypes: ["comida", "cena", "snack"],
    risks: [],
  },
  {
    id: "salmon",
    name: "Salmón cocinado",
    category: "proteina",
    kcal: 208,
    protein: 22,
    carbs: 0,
    fats: 13,
    defaultGrams: 150,
    visualPortion: "un lomo del tamaño de la palma",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "merluza",
    name: "Merluza cocinada",
    category: "proteina",
    kcal: 90,
    protein: 19,
    carbs: 0,
    fats: 1.4,
    defaultGrams: 180,
    visualPortion: "dos lomos medianos",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "jamon_cocido",
    name: "Jamón cocido extra",
    category: "proteina",
    kcal: 110,
    protein: 19,
    carbs: 1.5,
    fats: 3,
    defaultGrams: 100,
    visualPortion: "5-6 lonchas",
    mealTypes: ["desayuno", "snack", "cena"],
    risks: [],
    notes: "Elegir una versión sin lactosa, sorbitol ni azúcares añadidos.",
  },
  {
    id: "tofu_firme",
    name: "Tofu firme",
    category: "proteina",
    kcal: 144,
    protein: 17,
    carbs: 2.8,
    fats: 8.7,
    defaultGrams: 160,
    visualPortion: "medio bloque",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "yogur_sin_lactosa",
    name: "Yogur griego natural sin lactosa",
    category: "lacteo",
    kcal: 95,
    protein: 8.5,
    carbs: 4.5,
    fats: 4.5,
    defaultGrams: 200,
    visualPortion: "un bol individual",
    mealTypes: ["desayuno", "snack"],
    risks: [],
  },
  {
    id: "leche_sin_lactosa",
    name: "Leche semidesnatada sin lactosa",
    category: "lacteo",
    kcal: 46,
    protein: 3.2,
    carbs: 4.8,
    fats: 1.6,
    defaultGrams: 250,
    visualPortion: "un vaso grande",
    mealTypes: ["desayuno", "snack"],
    risks: [],
  },
  {
    id: "proteina_isolate",
    name: "Proteína whey isolate sin lactosa",
    category: "proteina",
    kcal: 370,
    protein: 86,
    carbs: 3,
    fats: 2,
    defaultGrams: 30,
    visualPortion: "un cacito",
    mealTypes: ["desayuno", "snack"],
    risks: [],
  },
  {
    id: "arroz_blanco_cocido",
    name: "Arroz blanco cocido",
    category: "carbohidrato",
    kcal: 130,
    protein: 2.7,
    carbs: 28.2,
    fats: 0.3,
    defaultGrams: 180,
    visualPortion: "un cuenco mediano",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "patata_cocida",
    name: "Patata cocida o al horno",
    category: "carbohidrato",
    kcal: 87,
    protein: 1.9,
    carbs: 20.1,
    fats: 0.1,
    defaultGrams: 280,
    visualPortion: "dos patatas medianas",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "avena",
    name: "Copos de avena",
    category: "carbohidrato",
    kcal: 389,
    protein: 16.9,
    carbs: 66.3,
    fats: 6.9,
    defaultGrams: 60,
    visualPortion: "seis cucharadas colmadas",
    mealTypes: ["desayuno", "snack"],
    risks: [],
  },
  {
    id: "quinoa_cocida",
    name: "Quinoa cocida",
    category: "carbohidrato",
    kcal: 120,
    protein: 4.4,
    carbs: 21.3,
    fats: 1.9,
    defaultGrams: 180,
    visualPortion: "un cuenco mediano",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "pan_sin_gluten",
    name: "Pan sin gluten sencillo",
    category: "carbohidrato",
    kcal: 245,
    protein: 4.5,
    carbs: 48,
    fats: 3.5,
    defaultGrams: 80,
    visualPortion: "dos rebanadas grandes",
    mealTypes: ["desayuno", "snack", "cena"],
    risks: [],
    notes: "Revisar que no contenga miel, inulina, sorbitol o concentrados de fruta.",
  },
  {
    id: "tortitas_arroz",
    name: "Tortitas de arroz",
    category: "carbohidrato",
    kcal: 387,
    protein: 8,
    carbs: 81,
    fats: 3,
    defaultGrams: 36,
    visualPortion: "cuatro tortitas",
    mealTypes: ["desayuno", "snack"],
    risks: [],
  },
  {
    id: "tortilla_maiz",
    name: "Tortilla de maíz",
    category: "carbohidrato",
    kcal: 218,
    protein: 5.7,
    carbs: 44.6,
    fats: 2.9,
    defaultGrams: 90,
    visualPortion: "tres tortillas pequeñas",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "aceite_oliva",
    name: "Aceite de oliva virgen extra",
    category: "grasa",
    kcal: 884,
    protein: 0,
    carbs: 0,
    fats: 100,
    defaultGrams: 10,
    visualPortion: "una cucharada rasa",
    mealTypes: ["desayuno", "comida", "cena"],
    risks: [],
  },
  {
    id: "crema_cacahuete",
    name: "Crema de cacahuete 100%",
    category: "grasa",
    kcal: 588,
    protein: 25,
    carbs: 20,
    fats: 50,
    defaultGrams: 20,
    visualPortion: "una cucharada colmada",
    mealTypes: ["desayuno", "snack"],
    risks: [],
  },
  {
    id: "nueces",
    name: "Nueces",
    category: "grasa",
    kcal: 654,
    protein: 15.2,
    carbs: 13.7,
    fats: 65.2,
    defaultGrams: 20,
    visualPortion: "un puñado pequeño",
    mealTypes: ["desayuno", "snack"],
    risks: [],
  },
  {
    id: "calabacin",
    name: "Calabacín cocinado",
    category: "verdura",
    kcal: 17,
    protein: 1.2,
    carbs: 3.1,
    fats: 0.3,
    defaultGrams: 180,
    visualPortion: "medio plato",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "zanahoria",
    name: "Zanahoria cocinada",
    category: "verdura",
    kcal: 35,
    protein: 0.8,
    carbs: 8.2,
    fats: 0.2,
    defaultGrams: 140,
    visualPortion: "dos zanahorias medianas",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "espinacas",
    name: "Espinacas cocinadas",
    category: "verdura",
    kcal: 23,
    protein: 3,
    carbs: 3.8,
    fats: 0.3,
    defaultGrams: 150,
    visualPortion: "medio plato",
    mealTypes: ["desayuno", "comida", "cena"],
    risks: [],
  },
  {
    id: "pepino",
    name: "Pepino",
    category: "verdura",
    kcal: 15,
    protein: 0.7,
    carbs: 3.6,
    fats: 0.1,
    defaultGrams: 150,
    visualPortion: "medio pepino grande",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "judia_verde",
    name: "Judía verde cocinada",
    category: "verdura",
    kcal: 31,
    protein: 1.8,
    carbs: 7,
    fats: 0.2,
    defaultGrams: 180,
    visualPortion: "medio plato",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "lechuga",
    name: "Lechuga",
    category: "verdura",
    kcal: 15,
    protein: 1.4,
    carbs: 2.9,
    fats: 0.2,
    defaultGrams: 100,
    visualPortion: "un bol grande",
    mealTypes: ["comida", "cena"],
    risks: [],
  },
  {
    id: "tomate",
    name: "Tomate",
    category: "verdura",
    kcal: 18,
    protein: 0.9,
    carbs: 3.9,
    fats: 0.2,
    defaultGrams: 120,
    visualPortion: "un tomate mediano",
    mealTypes: ["desayuno", "comida", "cena"],
    risks: [],
  },
  {
    id: "fresas",
    name: "Fresas",
    category: "fruta",
    kcal: 32,
    protein: 0.7,
    carbs: 7.7,
    fats: 0.3,
    defaultGrams: 100,
    visualPortion: "seis fresas medianas",
    mealTypes: ["desayuno", "snack"],
    risks: ["fructosa"],
    notes: "Solo incluir si el usuario tolera esta ración.",
  },
  {
    id: "kiwi",
    name: "Kiwi",
    category: "fruta",
    kcal: 61,
    protein: 1.1,
    carbs: 14.7,
    fats: 0.5,
    defaultGrams: 75,
    visualPortion: "un kiwi",
    mealTypes: ["desayuno", "snack"],
    risks: ["fructosa"],
    notes: "Solo incluir si el usuario tolera esta ración.",
  },
  {
    id: "platano_poco_maduro",
    name: "Plátano poco maduro",
    category: "fruta",
    kcal: 89,
    protein: 1.1,
    carbs: 22.8,
    fats: 0.3,
    defaultGrams: 90,
    visualPortion: "un plátano pequeño",
    mealTypes: ["desayuno", "snack"],
    risks: ["fructosa", "sorbitol"],
    notes: "Solo incluir si el usuario ha confirmado tolerancia.",
  },
];

export const nutritionFoodMap = new Map(nutritionFoods.map((food) => [food.id, food]));

function round1(value: number): number {
  return Math.round(value * 10) / 10;
}

export function calculateIngredient(foodId: string, grams: number): CalculatedIngredient | null {
  const food = nutritionFoodMap.get(foodId);
  if (!food) return null;

  const safeGrams = Math.max(5, Math.min(600, Math.round(grams)));
  const factor = safeGrams / 100;
  return {
    food_id: food.id,
    name: food.name,
    grams: safeGrams,
    visual_portion: food.visualPortion,
    calories: round1(food.kcal * factor),
    protein: round1(food.protein * factor),
    carbs: round1(food.carbs * factor),
    fats: round1(food.fats * factor),
  };
}

export function nutritionCatalogForPrompt(): string {
  return nutritionFoods
    .map((food) => {
      const risks = food.risks.length ? food.risks.join(",") : "ninguno";
      return [
        food.id,
        food.name,
        food.category,
        `kcal:${food.kcal}`,
        `P:${food.protein}`,
        `C:${food.carbs}`,
        `G:${food.fats}`,
        `racion:${food.defaultGrams}g`,
        `comidas:${food.mealTypes.join(",")}`,
        `riesgos:${risks}`,
      ].join("|");
    })
    .join("\n");
}
